name: Deploy Next.js to AWS EC2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: |
          docker build -t nextjs-app .
          docker save nextjs-app -o nextjs-app.tar  # Save Docker image as a tar file

      - name: Copy Docker Image to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_SSH_KEY }}
          source: "nextjs-app.tar"
          target: "/home/ubuntu"

      - name: SSH into EC2 and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            sudo docker stop nextjs-app || true
            sudo docker rm nextjs-app || true
            sudo docker load -i /home/ubuntu/nextjs-app.tar  # Load Docker image from tar file
            sudo docker run -d -p 3000:3000 --name nextjs-app nextjs-app
